# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

executors:
    docker:
      - image: jrcodes/laravel57-php73
    working_directory: ~/healthier

jobs:
  test:
    executor: docker
    steps:
      - checkout
      - run:
          name: Download Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            php composer.phar self-update
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Run Composer Install
          command: |
            composer install -n --prefer-dist
      - run:
          name: Run Unit Test
          command: |
            php ./vendor/bin/phpunit

workflows:
  version: 2
  test_build_push:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v.*/